keys:
  - &primary age1fyfvzdpefunekr7tf0fdqa85l7jvk6x2psrrwa26ckleln57hysssvuyzq
  - &orange age1sksc9cej58gwd9d7hh7zyc4jxsl40qjuqexkz6eqf99zhdkw4q3see367c
  - &lenovo age12ky2dfcwe9zm3lth6epkvy4mth93xs6snpcne744knqenflk4s0s0puu96
  - &wsl age1fxjynyzl83dlcj06509k8pc6ndpekgf5lajmkupx5j3ptv6ceehqr4hly6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *primary
        - *orange
        - *lenovo
        - *wsl