keys:
  - &main age130m46e8lm94zaew5zjjkcp5y8wf9cx6dr7hpl2w42tlmdgmlla3qutn0zr
  - &primary age1fyfvzdpefunekr7tf0fdqa85l7jvk6x2psrrwa26ckleln57hysssvuyzq
  - &orange age1546c2ausu2edta05gctcgvpc44acwqwjzprnv3fzjdwrphaqsu9qm78k4c
  - &orange2 age1eezq6dhs9pac77kj4xdfwvu4lgs9w2klmmxjfrmwghs44zgzapaqr235c6
  - &lenovo age12ky2dfcwe9zm3lth6epkvy4mth93xs6snpcne744knqenflk4s0s0puu96
  - &wsl age1yaxygnesy6722l9j98wkngj0xgz7fwn2e7tra2ztp7gq8sf2jdaqcaleja
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *main
        - *primary
        - *orange
        - *orange2
        - *lenovo
        - *wsl
