keys:
  - &primary age1fyfvzdpefunekr7tf0fdqa85l7jvk6x2psrrwa26ckleln57hysssvuyzq
  - &orange age1phgfzrnur7r54gpchccw8p2hnqqenz39rlqpnveepwyt926v650qdxf5ut
  - &lenovo age12ky2dfcwe9zm3lth6epkvy4mth93xs6snpcne744knqenflk4s0s0puu96
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *primary
        - *orange
        - *lenovo