{ pkgs, ... }:
{

  networking.wireguard.interfaces = {
    wg0 = {
      ips = [ "10.100.0.2/24" ];
      mtu = 1420;
      listenPort = 51820;

      privateKeyFile = "/etc/wireguard/private.key";

      peers = [
        {
          publicKey = "JK+BwkTEpVUSVoKwa2TRi1Q6MQd0YNovuFKXNAT4MyU=";
          allowedIPs = [ "10.100.0.1/32" ];
          endpoint = "37.120.168.146:51820";
          persistentKeepalive = 25;
        }

      ];
    };
  };

  # wg0 firewall openings are generated by
  # modules/infrastructure/service-firewall.nix from infra/services.nix
}
